tatuya.exe: main.obj logoDisplay.obj userManeger.obj userRegistraition.obj userDelete.obj userDisplay.obj allUsers.obj latest10.obj finger.obj dvdManeger.obj dvdRegistraition.obj dvdDelete.obj dvdDisplay.obj alldvds.obj latest11.obj finger2.obj dvdRental.obj dvdReturn.obj userHistory.obj nowRental.obj
	bcc32 -etatuya.exe main.obj logoDisplay.obj userManeger.obj userRegistraition.obj userDelete.obj userDisplay.obj allUsers.obj latest10.obj finger.obj dvdManeger.obj dvdRegistraition.obj dvdDelete.obj dvdDisplay.obj alldvds.obj latest11.obj finger2.obj dvdRental.obj dvdReturn.obj userHistory.obj nowRental.obj
main.obj: main.c
	bcc32 -c main.c
logoDisplay.obj: logoDisplay.c
	bcc32 -c logoDisplay.c
userManeger.obj: userManeger.c
	bcc32 -c userManeger.c
userRegistraition.obj: userRegistraition.c
	bcc32 -c userRegistraition.c
userDelete.obj: userDelete.c
	bcc32 -c userDelete.c
userDisplay.obj: userDisplay.c
	bcc32 -c userDisplay.c
allUsers.obj: allUsers.c
	bcc32 -c allUsers.c
latest10.obj: latest10.c
	bcc32 -c latest10.c
finger.obj: finger.c
	bcc32 -c finger.c
dvdManeger.obj: dvdManeger.c
	bcc32 -c dvdManeger.c
dvdRegistraition.obj: dvdRegistraition.c
	bcc32 -c dvdRegistraition.c
dvdDelete.obj: dvdDelete.c
	bcc32 -c dvdDelete.c
dvdDisplay.obj: dvdDisplay.c
	bcc32 -c dvdDisplay.c
alldvds.obj: alldvds.c
	bcc32 -c alldvds.c
latest11.obj: latest11.c
	bcc32 -c latest11.c
finger2.obj: finger2.c
	bcc32 -c finger2.c
dvdRental.obj: dvdRental.c
	bcc32 -c dvdRental.c
dvdReturn.obj: dvdReturn.c
	bcc32 -c dvdReturn.c
userHistory.obj: userHistory.c
	bcc32 -c userHistory.c
nowRental.obj: nowRental.c
	bcc32 -c nowRental.c


clean:
	del *.obj
	del *.tds
